export const categorias = [
  {
    id: 1,
    titulo: "Routers",
    imagen: "/Routers.png",
    link: "/Routers",
  },
  {
    id: 2,
    titulo: "Switches",
    imagen: "/Swithes.png",
    link: "/Switches",
  },
  {
    id: 3,
    titulo: "Puntos de Acceso",
    imagen: "/PuntosAcceso.png",
    link: "/PuntosDeAcceso",
  },
  {
    id: 4,
    titulo: "Accesorios",
    imagen: "/Accesorios.png",
    link: "/Accesorios",
  },
];

export const routers = [
  {
    id: 1,
    categoria: "Routers",
    imagen: "/2136ax_right_H1125.png",
    titulo: "Vigor 2136 Series",
    tituloMenu: "Vigor 2136",
    descripcion1: "WAN Ethernet de 2,5 Gigabits",
    descripcion2: "50k Sesiones NAT",
    descripcion3: "16 VPN Simultáneas",
    descripcion4: "Seguridad mejorada con IAM",
    descripcion5: "Modelo Wi-Fi 802.11ax",
    link: "/detalleDeProducto/1",
    subTitulo: "Router confiable para oficinas pequeñas y hogares",
    descripcionLarga:
      "La serie Vigor2136 es un router VPN de banda ancha con puerto WAN de 2.5G para ofrecer una alta velocidad que satisface las crecientes demandas de red de las empresas. Ofrece un rendimiento de hasta 2.3 Gbps sin sacrificar las funciones de control de ancho de banda. El router está equipado con funciones de nivel empresarial, como filtrado de contenido web, política de enrutamiento, QoS basado en aplicaciones y más. La serie incluye modelos con Wi-Fi 802.11ax integrado.",
    masInfo: "https://www.draytek.com/products/vigor2136",
    imagen2: "/2136ax_interface.png",
    descripcionDetalle1: "1x 2.5G WAN, 1x 2.5G LAN/WAN",
    descripcionDetalle2: "16 VPN",
    descripcionDetalle3: "Wi-Fi AX 3000",
    descripcionDetalle4: "50k Sesiones",
    subDescripcionDetalle1: "",
    subDescripcionDetalle2: "Rendimiento IPsec de hasta 390 Mbps",
    subDescripcionDetalle3: "Velocidad máxima 3 Gbps modelo ax",
    subDescripcionDetalle4: "Recomendado para una red de 15 hosts",
    entrada1: "Botón WLAN / WPS (modelo ax)",
    entrada2: "Botón de Reset",
    entrada3: "Puerto WAN 1 x 2,5 GbE RJ-45",
    entrada4: "Puerto LAN / WAN 1 x 2,5 GbE RJ-45",
    entrada5: "Puerto LAN 3 x GbE RJ-45",
    entrada6: "2 x USB 2.0",
    entrada7: "Interruptor de encendido / apagado",
    entrada8: "Entrada de alimentación",
    entrada9: "Antena inalámbrica (modelo ax)",
    entrada10: "",
    entrada11: "",
    entrada12: "",
  },
  {
    id: 2,
    categoria: "Routers",
    imagen: "/2927ac_right_new_H1125.png",
    titulo: "Vigor 2927 Series",
    tituloMenu: "Vigor 2927",
    descripcion1: "Dual WAN Ethernet Gigabit",
    descripcion2: "60k Sesiones NAT",
    descripcion3: "50 VPN Simultáneas",
    descripcion4: "Modelo Wi-Fi 802.11ac",
    descripcion5: "Modelo Wi-Fi 802.11ax",
    link: "/detalleDeProducto/2",
    subTitulo: "El Router para toda necesidad de las PyMEs.",
    descripcionLarga:
      "La serie Vigor 2927 es un Router Firewall Dual WAN Ethernet que proporciona balanceo de carga y redundancia de enlaces para la continuidad de su negocio. Con VPN, QoS, políticas de ruteo, firewall, filtrado de contenido, administración de ancho de banda, portal de punto de acceso cautivo y mucho más, este es el Router definitivo para toda necesidad de las PyMEs. La serie incluye modelos con WiFi 802.11ac o WiFi 802.11ax integrados.",
    masInfo: "https://www.draytek.com/products/vigor2927",
    imagen2: "/2927Vac_interface_new.png",
    descripcionDetalle1: "50 VPN",
    descripcionDetalle2: "25 VPN SSL",
    descripcionDetalle3: "Wi-Fi AX 3000",
    descripcionDetalle4: "60k Sesiones",
    subDescripcionDetalle1: "Rendimiento IPsec de hasta 800 Mbps",
    subDescripcionDetalle2: "Rendimiento de hasta 120 Mbps",
    subDescripcionDetalle3: "Velocidad máxima 3 Gbps modelo ax",
    subDescripcionDetalle4: "Recomendado para una red de 50 hosts",
    entrada1: "Antena inalámbrica (modelo ac / ax)",
    entrada2: "Botón de Reset",
    entrada3: "Botón WLAN / WPS (modelo ac / ax)",
    entrada4: "Indicador LED",
    entrada5: "2 x USB 2.0",
    entrada6: "Puerto WAN 1 x GbE RJ-45",
    entrada7: "Puerto WAN / LAN 1 x GbE RJ-45",
    entrada8: "Puerto LAN 5 x GbE RJ-45",
    entrada9: "2 x FXS para VoIP (modelo V)",
    entrada10: "Interruptor de encendido / apagado",
    entrada11: "Entrada de alimentación",
    entrada12: "",
  },
  {
    id: 3,
    categoria: "Routers",
    imagen: "/2962_front_H1125.png",
    titulo: "Vigor 2962",
    tituloMenu: "Vigor 2962",
    descripcion1: "3 WAN Ethernet",
    descripcion2: "1 Puerto GbE / SFP",
    descripcion3: "300k Sesiones NAT",
    descripcion4: "200 VPN Simultáneas",
    descripcion5: "",
    link: "/detalleDeProducto/3",
    subTitulo: "Router corporativo WAN múltiple de alto rendimiento",
    descripcionLarga:
      "El Vigor 2962 es un router firewall dinámico y de alto rendimiento con puertos WAN / LAN configurables. Con la opción de un puerto de 2,5 GbE, un puerto de fibra de 1 GbE y dos puertos de 1 GbE, los usuarios pueden configurar cuatro de los puertos como WAN para balanceo de carga y failover, y disfrutar de un rendimiento NAT total de 2,2 Gbps.",
    masInfo: "https://www.draytek.com/products/vigor2962",
    imagen2: "/2962_interface.png",
    descripcionDetalle1: "Hasta 4 WAN",
    descripcionDetalle2: "200 VPN",
    descripcionDetalle3: "2.2 Gbps",
    descripcionDetalle4: "300k Sesiones",
    subDescripcionDetalle1: "Incluyendo Ethernet 2.5G y SFP",
    subDescripcionDetalle2: "Rendimiento IPsec de hasta 1 Gbps",
    subDescripcionDetalle3: "Rendimiento máximo de NAT",
    subDescripcionDetalle4: "Recomendado para una red de 200 hosts",
    entrada1: "Entrada de alimentación",
    entrada2: "Interruptor de encendido / apagado",
    entrada3: "Botón de Reset",
    entrada4: "Indicador LED",
    entrada5: "Puerto WAN / LAN 1 x 2,5 GbE RJ-45",
    entrada6: "Puerto WAN / LAN 1 x GbE / SFP",
    entrada7: "Puerto WAN / LAN 2 x GbE RJ-45",
    entrada8: "Puerto LAN 2 x GbE RJ-45",
    entrada9: "1 x USB 2.0 + 1 x USB 3.0",
    entrada10: "",
    entrada11: "",
    entrada12: "",
  },
  {
    id: 4,
    categoria: "Routers",
    imagen: "/3912_front_H1125.png",
    titulo: "Vigor 3912",
    tituloMenu: "Vigor 3912",
    descripcion1: "6 WAN Ethernet",
    descripcion2: "2 Puertos SFP+ 10G",
    descripcion3: "1000k Sesiones NAT",
    descripcion4: "500 VPN Simultáneas",
    descripcion5: "8GB RAM (DDR4)",
    link: "/detalleDeProducto/4",
    subTitulo: "Router corporativo WAN múltiple de máximo rendimiento",
    descripcionLarga:
      "El Vigor 3912 está diseñado para redes con alto consumo de ancho de banda e incorpora una CPU de cuatro núcleos a 2 GHz para una rápida velocidad de conexión, incluso con varios dispositivos conectados. El router cuenta con 8 interfaces WAN, incluyendo 2 SFP+ 10G para fibra óptica, 2 Ethernet 2,5G y 4 Ethernet 1G, lo que proporciona un rendimiento NAT ultrarrápido. Los puertos 1 a 8 se pueden configurar independientemente para WAN o LAN para ofrecer flexibilidad y optimizar el rendimiento del router. El Vigor 3912 puede funcionar como servidor VPN para establecer conexiones VPN de LAN to LAN o de usuarios remotos. Incluye funciones optimizadas para PYMES, como la autenticación VPN 2FA y VPN desde LAN, lo que garantiza una red VPN más segura y eficiente.",
    masInfo: "https://www.draytek.com/products/vigor3912",
    imagen2: "/3912_interface.png",
    descripcionDetalle1: "Hasta 8 WAN",
    descripcionDetalle2: "500 VPN",
    descripcionDetalle3: "CPU Quad-Core",
    descripcionDetalle4: "1000k Sesiones",
    subDescripcionDetalle1: "Incluyendo Ethernet 2.5G y SFP+ 10G",
    subDescripcionDetalle2: "Rendimiento IPsec de hasta 5.7 Gbps",
    subDescripcionDetalle3: "Rendimiento máximo de NAT 15.6 Gbps",
    subDescripcionDetalle4: "Recomendado para una red de 500 hosts",
    entrada1: "2 x USB 3.0",
    entrada2: "Botón de Reset",
    entrada3: "Puerto Consola RJ-45",
    entrada4: "Puerto WAN / LAN 2 x 10G SFP+",
    entrada5: "Puerto WAN / LAN 2 x 2,5 GbE RJ-45",
    entrada6: "Puerto WAN / LAN 4 x GbE RJ-45",
    entrada7: "Puerto LAN 4 x GbE RJ-45",
    entrada8: "",
    entrada9: "",
    entrada10: "",
    entrada11: "",
    entrada12: "",
  },
];

export const switches = [
  {
    id: 5,
    categoria: "Switches",
    imagen: "/G1080_front_H1125.png",
    titulo: "Vigor Switch G1080",
    tituloMenu: "SW G1080",
    descripcion1: "8 Puertos GbE",
    descripcion2: "Smart Lite",
    descripcion3: "Capacidad de conmutación de 16G",
    descripcion4: "",
    descripcion5: "",
    link: "/detalleDeProducto/5",
    subTitulo: "Switch Gigabit Smart Lite de 8 puertos",
    descripcionLarga:
      "El Vigor Switch G1080 es un Switch Gigabit Smart Lite de 8 puertos extremadamente compacto. Ofrece gestión básica, incluyendo VLAN 802.1q, calidad de servicio (QoS) 802.1p, agregación de enlaces, control de tormentas y prevención de bucles. Ideal para oficinas pequeñas y hogares con necesidades de eficiencia y seguridad de red.",
    masInfo: "https://www.draytek.com/products/vigorswitch-G1080",
    imagen2: "",
    descripcionDetalle1: "8 Puertos",
    descripcionDetalle2: "8 VLANs",
    descripcionDetalle3: "325g",
    descripcionDetalle4: "3.3W",
    subDescripcionDetalle1: "GbE RJ-45",
    subDescripcionDetalle2: "Soporta 802.1q Tag-based",
    subDescripcionDetalle3: "¾ del peso de una pelota de fútbol",
    subDescripcionDetalle4: "Bajo consumo de energía",
    entrada1: "",
    entrada2: "",
    entrada3: "",
    entrada4: "",
    entrada5: "",
    entrada6: "",
    entrada7: "",
    entrada8: "",
    entrada9: "",
    entrada10: "",
    entrada11: "",
    entrada12: "",
  },
  {
    id: 6,
    categoria: "Switches",
    imagen: "/G1282_front_H1125.png",
    titulo: "Vigor Switch G1282",
    tituloMenu: "SW G1282",
    descripcion1: "24 Puertos GbE",
    descripcion2: "4 Puertos GbE / SFP",
    descripcion3: "Web Smart",
    descripcion4: "Capacidad de conmutación de 56G",
    descripcion5: "1U Rackmount",
    link: "/detalleDeProducto/6",
    subTitulo: "Switch Gigabit Web Smart de 28 puertos",
    descripcionLarga:
      "El Vigor Switch G1282 es un Switch Gigabit Web Smart. Cuenta con 24 puertos GbE y 4 puertos combinados GbE/SFP. Equipado con funciones de nivel empresarial, como detección y prevención de conflictos de IP, vigilancia ONVIF y vigilancia de ping, el Vigor Switch G1282 es un switch administrable que ofrece seguridad y estabilidad de red en entornos de tamaño mediano.",
    masInfo: "https://www.draytek.com/products/vigorswitch-G1282",
    imagen2: "/G1282_interface.png",
    descripcionDetalle1: "24 Puertos GbE",
    descripcionDetalle2: "4 Puertos GbE / SFP",
    descripcionDetalle3: "56 Gbps",
    descripcionDetalle4: "4.2 Mbit",
    subDescripcionDetalle1: "Gigabit Ethernet RJ-45",
    subDescripcionDetalle2: "Gigabit Ethernet RJ-45 / SFP",
    subDescripcionDetalle3: "Capacidad de conmutación",
    subDescripcionDetalle4: "Tamaño del búfer",
    entrada1: "Entrada de alimentación",
    entrada2: "Indicador LED",
    entrada3: "Botón de Reset",
    entrada4: "24 x GbE RJ-45",
    entrada5: "4 x GbE / SFP",
    entrada6: "",
    entrada7: "",
    entrada8: "",
    entrada9: "",
    entrada10: "",
    entrada11: "",
    entrada12: "",
  },
  {
    id: 7,
    categoria: "Switches",
    imagen: "/G2282x_front_H1125.png",
    titulo: "Vigor Switch G2282x",
    tituloMenu: "SW G2282x",
    descripcion1: "24 Puertos GbE",
    descripcion2: "4 Puertos SFP+ 10G",
    descripcion3: "Administrable Capa 2+",
    descripcion4: "Capacidad de conmutación de 128G",
    descripcion5: "1U Rackmount",
    link: "/detalleDeProducto/7",
    subTitulo: "Switch Gigabit Administrable Capa 2+ de 28 puertos",
    descripcionLarga:
      "El Vigor G2282x es un Switch Gigabit Administrable de Capa 2+. Cuenta con 24 puertos GbE y 4 puertos SFP+ 10G. Además de la entrada de alimentación AC, el Vigor Switch G2282x también cuenta con una entrada de DC como fuente de alimentación adicional, lo que ayuda a garantizar un funcionamiento ininterrumpido y a proteger los dispositivos conectados en caso de fallo de la alimentación de AC. Compatible con funciones avanzadas de Capa 3, como servidor DHCP y enrutamiento VLAN. Esto mejora la eficiencia de la red y garantiza una conectividad LAN ininterrumpida, incluso cuando la puerta de enlace está fuera de línea, lo que lo convierte en una excelente solución para redes con una demanda de tráfico creciente.",
    masInfo: "https://www.draytek.com/products/vigorswitch-g2282x",
    imagen2: "/G2282x_2.png",
    descripcionDetalle1: "24 Puertos GbE",
    descripcionDetalle2: "4 Puertos SFP+ 10G",
    descripcionDetalle3: "128 Gbps",
    descripcionDetalle4: "Energía de Backup",
    subDescripcionDetalle1: "Gigabit Ethernet RJ-45",
    subDescripcionDetalle2: "SFP+ 10G",
    subDescripcionDetalle3: "Capacidad de conmutación",
    subDescripcionDetalle4: "Toma de corriente redundante de 12V DC",
    entrada1: "Indicador de Stack ID",
    entrada2: "Botón de Stacking",
    entrada3: "Puerto Consola RJ-45",
    entrada4: "24 x GbE RJ-45",
    entrada5: "4 x 10G SFP+",
    entrada6: "Entrada de alimentación DC (backup)",
    entrada7: "Entrada de alimentación AC",
    entrada8: "",
    entrada9: "",
    entrada10: "",
    entrada11: "",
    entrada12: "",
  },
  {
    id: 8,
    categoria: "Switches",
    imagen: "/G2540x_front_H1125.png",
    titulo: "Vigor Switch G2540xs",
    tituloMenu: "SW G2540xs",
    descripcion1: "48 Puertos GbE",
    descripcion2: "6 Puertos SFP+ 10G",
    descripcion3: "Administrable Capa 2+",
    descripcion4: "Capacidad de conmutación de 216G",
    descripcion5: "1U Rackmount",
    link: "/detalleDeProducto/8",
    subTitulo: "Switch Gigabit Administrable Capa 2+ de 54 puertos",
    descripcionLarga:
      "El Vigor G2540xs es un Switch Gigabit Administrable de Capa 2+. Cuenta con 48 puertos GbE y 6 puertos SFP+ 10G. Al soportar funciones avanzadas de Capa 3, servidor DHCP y enrutamiento VLAN, el Vigor Switch G2540xs mejora la eficiencia de la red y ayuda a que su red LAN funcione de manera continua incluso cuando la puerta de enlace está fuera de línea, lo que es ideal para colocarlo como switch core para SME / SMB.",
    masInfo: "https://www.draytek.com/products/vigorswitch-g2540x",
    imagen2: "/G2540x_interface.png",
    descripcionDetalle1: "48 Puertos GbE",
    descripcionDetalle2: "6 Puertos SFP+ 10G",
    descripcionDetalle3: "216 Gbps",
    descripcionDetalle4: "16 Mbit",
    subDescripcionDetalle1: "Gigabit Ethernet RJ-45",
    subDescripcionDetalle2: "SFP+ 10G",
    subDescripcionDetalle3: "Capacidad de conmutación",
    subDescripcionDetalle4: "Tamaño del búfer",
    entrada1: "Entrada de alimentación",
    entrada2: "Botón de Reset",
    entrada3: "Indicador LED",
    entrada4: "48 x GbE RJ-45",
    entrada5: "6 x 10G SFP+",
    entrada6: "Puerto Consola RJ-45",
    entrada7: "",
    entrada8: "",
    entrada9: "",
    entrada10: "",
    entrada11: "",
    entrada12: "",
  },
  {
    id: 9,
    categoria: "Switches",
    imagen: "/P2100_front_H1125.png",
    titulo: "Vigor Switch P2100",
    tituloMenu: "SW P2100",
    descripcion1: "8 Puertos GbE PoE / PoE+",
    descripcion2: "2 Puertos SFP",
    descripcion3: "Capacidad de conmutación de 20G",
    descripcion4: "140W PoE Power Budget",
    descripcion5: "1U Rackmount",
    link: "/detalleDeProducto/9",
    subTitulo: "Switch PoE Gigabit Administrable Capa 2+ de 10 puertos",
    descripcionLarga:
      "El Vigor Switch P2100 es un Switch Gigabit PoE Administrable de Capa 2+ compacto, ideal para hogares inteligentes y sucursales / sitios remotos. Cuenta con 2 puertos SFP GbE, 8 puertos Gigabit Ethernet PoE / PoE+ con un Power Budget de 140W y un puerto de consola. Con funciones de Capa 3, como servidor DHCP y enrutamiento VLAN, el Vigor Switch P2100 mejora la sostenibilidad y la eficiencia de la red local, independientemente de la puerta de enlace. Además, con detección y prevención de conflictos de IP, vigilancia ONVIF, ping watchdog y mucho más, este switch equilibrado ofrece funciones avanzadas en entornos pequeños.",
    masInfo: "https://www.draytek.com/products/vigorswitch-p2100",
    imagen2: "/P2100_interface.png",
    descripcionDetalle1: "8 Puertos PoE GbE",
    descripcionDetalle2: "2 Puertos SFP",
    descripcionDetalle3: "20 Gbps",
    descripcionDetalle4: "140 watts",
    subDescripcionDetalle1: "Gigabit Ethernet RJ-45",
    subDescripcionDetalle2: "SFP",
    subDescripcionDetalle3: "Capacidad de conmutación",
    subDescripcionDetalle4: "PoE Power Budget",
    entrada1: "Entrada de alimentación",
    entrada2: "Indicador LED",
    entrada3: "8 x PoE GbE RJ-45",
    entrada4: "Puerto Consola RJ-45",
    entrada5: "2 x SFP",
    entrada6: "Botón de Reset",
    entrada7: "",
    entrada8: "",
    entrada9: "",
    entrada10: "",
    entrada11: "",
    entrada12: "",
  },
  {
    id: 10,
    categoria: "Switches",
    imagen: "/P1282_front_H1125.png",
    titulo: "Vigor Switch P1282",
    tituloMenu: "SW P1282",
    descripcion1: "24 Puertos GbE PoE / PoE+",
    descripcion2: "4 Puertos GbE / SFP",
    descripcion3: "Web Smart",
    descripcion4: "Capacidad de conmutación de 56G",
    descripcion5: "1U Rackmount",
    link: "/detalleDeProducto/10",
    subTitulo: "Switch PoE Gigabit Web Smart de 28 puertos",
    descripcionLarga:
      "El Vigor Switch P1282 es un Switch PoE Gigabit Web Smart. Cuenta con 24 puertos GbE PoE / PoE+ con un Power Budget de 400W y 4 puertos combinados GbE / SFP. Equipado con funciones de nivel empresarial, como detección y prevención de conflictos de IP, vigilancia ONVIF y vigilancia de ping, el Vigor Switch P1282 es un switch administrable que ofrece seguridad y estabilidad de red en entornos de tamaño mediano.",
    masInfo: "https://www.draytek.com/products/vigorswitch-p1282",
    imagen2: "/P1282_interface.png",
    descripcionDetalle1: "24 Puertos PoE GbE",
    descripcionDetalle2: "4 Puertos GbE / SFP",
    descripcionDetalle3: "56 Gbps",
    descripcionDetalle4: "400 Watts",
    subDescripcionDetalle1: "Gigabit Ethernet RJ-45",
    subDescripcionDetalle2: "Gigabit Ethernet RJ-45 / SFP",
    subDescripcionDetalle3: "Capacidad de conmutación",
    subDescripcionDetalle4: "PoE Power Budget",
    entrada1: "Entrada de alimentación",
    entrada2: "Indicador LED",
    entrada3: "Botón de Reset",
    entrada4: "24 x PoE GbE RJ-45",
    entrada5: "4 x GbE / SFP",
    entrada6: "",
    entrada7: "",
    entrada8: "",
    entrada9: "",
    entrada10: "",
    entrada11: "",
    entrada12: "",
  },
];

export const puntosDeAcceso = [
  {
    id: 11,
    categoria: "Puntos de Acceso",
    imagen: "/805_v2_right_H1125.png",
    titulo: "Vigor AP 805",
    tituloMenu: "AP 805",
    descripcion1: "Wi-Fi AX 3000",
    descripcion2: "Escritorio",
    descripcion3: "1 x 2,5 GbE + 1 x GbE",
    descripcion4: "",
    descripcion5: "",
    link: "/detalleDeProducto/11",
    subTitulo: "AP Wi-Fi 6 avanzado con diseño moderno",
    descripcionLarga:
      "El Vigor AP 805 es un innovador punto de acceso Wi-Fi 6 de doble banda, diseñado para ofrecer un rendimiento inalámbrico excepcional con una estética moderna. Con una velocidad de enlace de 600 Mbps en la banda de 2,4 GHz y 2400 Mbps en la de 5 GHz, proporciona una conectividad inigualable para hogares, oficinas y entornos de alta densidad. Su sencilla carcasa blanca y diseño cilíndrico le da un aspecto impecable, ya sea sobre un escritorio, una estantería o cualquier espacio visible.",
    masInfo: "https://www.draytek.com/products/vigorap-805",
    imagen2: "/805_v2_port_interface.png",
    descripcionDetalle1: "Doble banda",
    descripcionDetalle2: "AX 3000",
    descripcionDetalle3: "1 x 2.5G LAN",
    descripcionDetalle4: "256 Usuarios",
    subDescripcionDetalle1: "2.4 GHz y 5 GHz",
    subDescripcionDetalle2: "600 Mbps en 2.4 GHz y 2.4 Gbps en 5 GHz",
    subDescripcionDetalle3: "Internet de alta velocidad",
    subDescripcionDetalle4: "2.4 GHz y 5 GHz compartidos simultáneamente",
    entrada1: "Botón Wireless Mesh",
    entrada2: "Botón de reset",
    entrada3: "Puerto LAN 1 x GbE RJ-45 (Gris)",
    entrada4: "Puerto LAN 1 x 2,5 GbE RJ-45 (Rojo)",
    entrada5: "Entrada de alimentación",
    entrada6: "",
    entrada7: "",
    entrada8: "",
    entrada9: "",
    entrada10: "",
    entrada11: "",
    entrada12: "",
  },
  {
    id: 12,
    categoria: "Puntos de Acceso",
    imagen: "/905_left_H1125.png",
    titulo: "Vigor AP 905",
    tituloMenu: "AP 905",
    descripcion1: "Wi-Fi AX 3000",
    descripcion2: "Escritorio / Pared",
    descripcion3: "1 x 2.5G + 4 x GbE",
    descripcion4: "Alimentación DC / PoE",
    descripcion5: "",
    link: "/detalleDeProducto/12",
    subTitulo: "AP Wi-Fi 6 potente para una mejor eficiencia de la red",
    descripcionLarga:
      "El Vigor AP 905 es un punto de acceso Wi-Fi 6 de doble banda que ofrece un rendimiento rápido de hasta 2,4 Gbps en la banda de 5 GHz y 600 Mbps en la banda de 2,4 GHz. Este punto de acceso admite 256 clientes simultáneos y proporciona una conectividad inalámbrica excelente y fiable. Gracias a su compatibilidad con redes mesh, puede ampliar la cobertura Wi-Fi de forma inalámbrica para mayor flexibilidad y optimizar el rendimiento.",
    masInfo: "https://www.draytek.com/products/vigorap-905",
    imagen2: "/905_port.png",
    descripcionDetalle1: "Doble banda",
    descripcionDetalle2: "AX 3000",
    descripcionDetalle3: "1 x 2.5G LAN",
    descripcionDetalle4: "256 Usuarios",
    subDescripcionDetalle1: "2.4 GHz y 5 GHz",
    subDescripcionDetalle2: "600 Mbps en 2.4 GHz y 2.4 Gbps en 5 GHz",
    subDescripcionDetalle3: "Internet de alta velocidad",
    subDescripcionDetalle4: "2.4 GHz y 5 GHz compartidos simultáneamente",
    entrada1: "Antena inalámbrica",
    entrada2: "Indicador LED",
    entrada3: "Entrada de alimentación",
    entrada4: "Interruptor de encendido / apagado",
    entrada5: "Botón WLAN / WPS",
    entrada6: "Botón de reset",
    entrada7: "Puerto LAN 1 x 2.5G RJ-45 (PoE)",
    entrada8: "Puerto LAN 4 x GbE RJ-45",
    entrada9: "1 x USB 2.0",
    entrada10: "",
    entrada11: "",
    entrada12: "",
  },
  {
    id: 13,
    categoria: "Puntos de Acceso",
    imagen: "/962C_front_H1125.png",
    titulo: "Vigor AP 962C",
    tituloMenu: "AP 962C",
    descripcion1: "Wi-Fi AX 3000",
    descripcion2: "Techo / Pared",
    descripcion3: "1 x 2,5 GbE",
    descripcion4: "Alimentación DC / PoE",
    descripcion5: "",
    link: "/detalleDeProducto/13",
    subTitulo: "AP Wi-Fi 6 potente para una mejor eficiencia de la red",
    descripcionLarga:
      "El Vigor AP 962C es un punto de acceso Wi-Fi 6 de doble banda que ofrece un rendimiento rápido de hasta 2,4 Gbps en la banda de 5 GHz y 600 Mbps en la banda de 2,4 GHz. Este punto de acceso admite 256 clientes simultáneos y proporciona una conectividad inalámbrica excelente y fiable. Gracias a su compatibilidad con redes mesh, puede ampliar la cobertura Wi-Fi de forma inalámbrica para mayor flexibilidad y optimizar el rendimiento.",
    masInfo: "https://www.draytek.com/products/vigorap-962c",
    imagen2: "/962C_port_interface.png",
    descripcionDetalle1: "Doble banda",
    descripcionDetalle2: "AX 3000",
    descripcionDetalle3: "1 x 2.5G LAN",
    descripcionDetalle4: "256 Usuarios",
    subDescripcionDetalle1: "2.4 GHz y 5 GHz",
    subDescripcionDetalle2: "600 Mbps en 2.4 GHz y 2.4 Gbps en 5 GHz",
    subDescripcionDetalle3: "Internet de alta velocidad",
    subDescripcionDetalle4: "2.4 GHz y 5 GHz compartidos simultáneamente",
    entrada1: "Puerto LAN 1 x 2,5 GbE RJ-45 (PoE)",
    entrada2: "Botón de reset",
    entrada3: "Entrada de alimentación",
    entrada4: "",
    entrada5: "",
    entrada6: "",
    entrada7: "",
    entrada8: "",
    entrada9: "",
    entrada10: "",
    entrada11: "",
    entrada12: "",
  },
  {
    id: 14,
    categoria: "Puntos de Acceso",
    imagen: "/918R_front_H1125.png",
    titulo: "Vigor AP 918R",
    tituloMenu: "AP 918R",
    descripcion1: "Wi-Fi AC 1300",
    descripcion2: "Poste / Pared",
    descripcion3: "Clasificación IP67",
    descripcion4: "Alimentación PoE",
    descripcion5: "",
    link: "/detalleDeProducto/14",
    subTitulo: "AP Wi-Fi 5 PoE para exteriores",
    descripcionLarga:
      "El Vigor AP 918R es un punto de acceso Wi-Fi 5 para exteriores. Ofrece una velocidad de enlace combinada de hasta 1,3 Gbps y una capacidad para más de 200 usuarios activos.",
    masInfo: "https://www.draytek.com/products/vigorap-918r",
    imagen2: "",
    descripcionDetalle1: "IP-67",
    descripcionDetalle2: "AC 1300",
    descripcionDetalle3: "-40° a 70° C",
    descripcionDetalle4: "256 Usuarios",
    subDescripcionDetalle1: "Clasificado como resistente al agua y al polvo",
    subDescripcionDetalle2: "Hasta 1.3 Gbps",
    subDescripcionDetalle3: "Amplio rango de temperatura de funcionamiento",
    subDescripcionDetalle4: "Como máximo 128 por radio",
    entrada1: "",
    entrada2: "",
    entrada3: "",
    entrada4: "",
    entrada5: "",
    entrada6: "",
    entrada7: "",
    entrada8: "",
    entrada9: "",
    entrada10: "",
    entrada11: "",
    entrada12: "",
  },
];

export const accesorios = [
  {
    id: 15,
    categoria: "Accesorios",
    imagen: "/rackmount.png",
    titulo: "Soporte de Rack",
    tituloMenu: "Rack Mount",
    descripcion1: "Para montar en un rack estándar de 19 pulgadas",
    descripcion2: "",
    descripcion3: "",
    descripcion4: "",
    descripcion5: "",
    link: "/detalleDeProducto/15",
    subTitulo: "Kit de montaje 1U de 19 pulgadas estándar para Routers Vigor",
    descripcionLarga:
      "Los soportes de rack se utilizan para montar el router en un rack estándar de 19 pulgadas.",
    masInfo: "https://www.draytek.com/products/rack-mount-bracket",
    imagen2: "",
    descripcionDetalle1: "",
    descripcionDetalle2: "",
    descripcionDetalle3: "",
    descripcionDetalle4: "",
    subDescripcionDetalle1: "",
    subDescripcionDetalle2: "",
    subDescripcionDetalle3: "",
    subDescripcionDetalle4: "",
    entrada1: "",
    entrada2: "",
    entrada3: "",
    entrada4: "",
    entrada5: "",
    entrada6: "",
    entrada7: "",
    entrada8: "",
    entrada9: "",
    entrada10: "",
    entrada11: "",
    entrada12: "",
  },
  {
    id: 16,
    categoria: "Accesorios",
    imagen: "/ANT-BAS1.png",
    titulo: "Base Magnética",
    tituloMenu: "Base Magnética",
    descripcion1: "Cable de extensión de 1 m",
    descripcion2: "",
    descripcion3: "",
    descripcion4: "",
    descripcion5: "",
    link: "/detalleDeProducto/16",
    subTitulo: "Base magnética y extensión para antenas DrayTek",
    descripcionLarga:
      "Las bases magnéticas con cable de extensión se utilizan para ubicar las antenas fuera del rack evitando obstrucciones y así encontrar la ubicación óptima.",
    masInfo: "https://www.draytek.com/products/ANT-BAS1",
    imagen2: "",
    descripcionDetalle1: "",
    descripcionDetalle2: "",
    descripcionDetalle3: "",
    descripcionDetalle4: "",
    subDescripcionDetalle1: "",
    subDescripcionDetalle2: "",
    subDescripcionDetalle3: "",
    subDescripcionDetalle4: "",
    entrada1: "",
    entrada2: "",
    entrada3: "",
    entrada4: "",
    entrada5: "",
    entrada6: "",
    entrada7: "",
    entrada8: "",
    entrada9: "",
    entrada10: "",
    entrada11: "",
    entrada12: "",
  },
  {
    id: 17,
    categoria: "Accesorios",
    imagen: "/dac-cx10-new.png",
    titulo: "DAC-CX10",
    tituloMenu: "DAC-CX10",
    descripcion1: "Cable de conexión SFP+ 10G de 1 m / 3 m",
    descripcion2: "",
    descripcion3: "",
    descripcion4: "",
    descripcion5: "",
    link: "/detalleDeProducto/17",
    subTitulo: "Cable de cobre pasivo de conexión directa SFP+ 10G",
    descripcionLarga:
      "El DAC-CX10 ofrece una solución conveniente para la transmisión y el almacenamiento de datos, ideal para que las empresas conecten switches a routers o servidores dentro de los racks. El DAC-CX10 está diseñado para proporcionar un enlace de datos de alta velocidad mediante cable de cobre y admite velocidades de 10 Gigabit Ethernet. Es compatible con SFP+ MSA para cumplir con los requisitos del estándar industrial de fibra y garantizar el rendimiento y la fiabilidad.",
    masInfo: "https://www.draytek.com/products/dac-cx10",
    imagen2: "",
    descripcionDetalle1: "",
    descripcionDetalle2: "",
    descripcionDetalle3: "",
    descripcionDetalle4: "",
    subDescripcionDetalle1: "",
    subDescripcionDetalle2: "",
    subDescripcionDetalle3: "",
    subDescripcionDetalle4: "",
    entrada1: "",
    entrada2: "",
    entrada3: "",
    entrada4: "",
    entrada5: "",
    entrada6: "",
    entrada7: "",
    entrada8: "",
    entrada9: "",
    entrada10: "",
    entrada11: "",
    entrada12: "",
  },
  {
    id: 18,
    categoria: "Accesorios",
    imagen: "/dam-fx10-20k.png",
    titulo: "DAM-FX10-20K",
    tituloMenu: "DAM-FX10-20K",
    descripcion1: "Transceptor óptico SFP+ monomodo",
    descripcion2: "",
    descripcion3: "",
    descripcion4: "",
    descripcion5: "",
    link: "/detalleDeProducto/18",
    subTitulo: "Módulo SFP+ de 10 G",
    descripcionLarga:
      "El DAM-FX10-20K es un transceptor óptico SFP+ monomodo, diseñado para conexiones Ethernet de 10 Gigabits a una distancia de hasta 20 km. Ofrece una solución conveniente y de alto rendimiento para la conectividad de fibra óptica de larga distancia.",
    masInfo: "https://www.draytek.com/products/dam-fx10-20k",
    imagen2: "",
    descripcionDetalle1: "",
    descripcionDetalle2: "",
    descripcionDetalle3: "",
    descripcionDetalle4: "",
    subDescripcionDetalle1: "",
    subDescripcionDetalle2: "",
    subDescripcionDetalle3: "",
    subDescripcionDetalle4: "",
    entrada1: "",
    entrada2: "",
    entrada3: "",
    entrada4: "",
    entrada5: "",
    entrada6: "",
    entrada7: "",
    entrada8: "",
    entrada9: "",
    entrada10: "",
    entrada11: "",
    entrada12: "",
  },
  {
    id: 19,
    categoria: "Accesorios",
    imagen: "/URL_Reputation.png",
    titulo: "URL Reputation",
    tituloMenu: "URL Reputation",
    descripcion1: "Servicio de inteligencia de amenazas",
    descripcion2: "",
    descripcion3: "",
    descripcion4: "",
    descripcion5: "",
    link: "/detalleDeProducto/19",
    subTitulo: "Control de contenido de navegación",
    descripcionLarga:
      "URL Reputation evalúa los sitios web y clasifica las URL en 82 categorías, con las cuales los administradores de TI pueden aplicar políticas para permitir, bloquear, supervisar o restringir el acceso según las necesidades de la empresa para aumentar la productividad y proteger a los usuarios de sitios web maliciosos.",
    masInfo: "https://www.draytek.com/solutions/url-ip-reputation",
    imagen2: "",
    descripcionDetalle1: "",
    descripcionDetalle2: "",
    descripcionDetalle3: "",
    descripcionDetalle4: "",
    subDescripcionDetalle1: "",
    subDescripcionDetalle2: "",
    subDescripcionDetalle3: "",
    subDescripcionDetalle4: "",
    entrada1: "",
    entrada2: "",
    entrada3: "",
    entrada4: "",
    entrada5: "",
    entrada6: "",
    entrada7: "",
    entrada8: "",
    entrada9: "",
    entrada10: "",
    entrada11: "",
    entrada12: "",
  },
];
