export const categorias = [
  {
    id: 1,
    titulo: "Routers",
    imagen: "/Routers.png",
    link: "/Routers",
  },
  {
    id: 2,
    titulo: "Switches",
    imagen: "/Swithes.png",
    link: "/Switches",
  },
  {
    id: 3,
    titulo: "Puntos de Acceso",
    imagen: "/PuntosAcceso.png",
    link: "/PuntosDeAcceso",
  },
  {
    id: 4,
    titulo: "Accesorios",
    imagen: "/Accesorios.png",
    link: "/Accesorios",
  },
];

export const routers = [
  {
    id: 1,
    categoria:"Routers",
    imagen: "/2915ac_left_H1125.png",
    titulo: "Vigor 2915 Series",
    descripcion1: "Dual Gigabit Ethernet WANs",
    descripcion2: "30k NAT Sessions",
    descripcion3: "16 Concurrent VPN",
    descripcion4: "Built-in 11ac Wave 2 WLAN (optional)",
    descripcion5: "",
    link: "/detalleDeProducto/1",
    subTitulo: "Router confiable para oficinas pequeñas y hogares",
    descripcionLarga:
      "La serie Vigor 2915 es una solución de gestión de red integrada diseñada para pequeñas empresas. La interfaz WAN principal es Gigabit Ethernet y los usuarios pueden agregar una conexión WAN secundaria utilizando el puerto LAN 4, el puerto USB o la interfaz Wi-Fi. La Dual WAN provee balanceo de carga o redundancia de enlaces para garantizar un acceso confiable a Internet. La serie Vigor 2915 también es un servidor VPN robusto para hasta 16 túneles simultáneos. Las funciones de firewall y filtrado de contenido pueden controlar el tráfico de red entrante y saliente, y también ofrece funciones de administración de ancho de banda que optimizan la asignación de ancho de banda y permite el mejor uso del ancho de banda disponible.",
    masInfo: "https://www.draytek.com/products/vigor2915",
    imagen2: "/2915ac_interface.png",
    descripcionDetalle1: "Hasta 2 WAN",
    descripcionDetalle2: "16 VPN",
    descripcionDetalle3: "8 VPN SSL",
    descripcionDetalle4: "30k Sesiones",
    subDescripcionDetalle1: "Balanceo de carga",
    subDescripcionDetalle2: "Rendimiento IPsec de hasta 250 Mbps",
    subDescripcionDetalle3: "Rendimiento de hasta 150 Mbps",
    subDescripcionDetalle4: "Recomendado para una red de 15 hosts",
    entrada1: "1- Entrada de alimentación",
    entrada2: "2- Interruptor de encendido / apagado",
    entrada3: "3- 1 x USB 2.0",
    entrada4: "4- Puerto WAN 1 x GbE RJ-45",
    entrada5: "5- Puerto LAN 3 x GbE RJ-45",
    entrada6: "6- Puerto WAN / LAN 1x GbE RJ-45",
    entrada7: "7- Botón WLAN / WPS (modelo ac)",
    entrada8: "8- Botón de reset",
    entrada9: "9- Antena inalámbrica (modelo ac)",
    entrada10: "",
    entrada11: "",
    entrada12: "",
  },
  {
    id: 2,
    categoria:"Routers",
    imagen: "/2927ac_left_new_H1125.png",
    titulo: "Vigor 2927 Series",
    descripcion1: "Dual Gigabit Ethernet WANs",
    descripcion2: "60k NAT Sessions",
    descripcion3: "50 Concurrent VPN",
    descripcion4: "Built-in 11ac Wave 2 WLAN (optional)",
    descripcion5: "Built-in 11ax WLAN (optional)",
    link: "/detalleDeProducto/2",
    subTitulo: "El Router para toda necesidad de las PyMEs.",
    descripcionLarga:
      "La serie Vigor 2927 es un Router Firewall Dual WAN Ethernet que proporciona balanceo de carga y redundancia de enlaces para la continuidad de su negocio. Con VPN, QoS, políticas de ruteo, firewall, filtrado de contenido, administración de ancho de banda, portal de punto de acceso cautivo y mucho más, este es el Router definitivo para toda necesidad de las PyMEs. La serie incluye modelos con WiFi 802.11ac o WiFi 802.11ax integrados.",
    masInfo: "https://www.draytek.com/products/vigor2927",
    imagen2: "/2927Vac_interface_new.png",
    descripcionDetalle1: "50 VPN",
    descripcionDetalle2: "25 VPN SSL",
    descripcionDetalle3: "Wi-Fi ax 3000",
    descripcionDetalle4: "60k Sesiones",
    subDescripcionDetalle1: "Rendimiento IPsec de hasta 250 Mbps",
    subDescripcionDetalle2: "Rendimiento de hasta 150 Mbps",
    subDescripcionDetalle3: "Velocidad máxima 3 Gbps Sólo modelo ax",
    subDescripcionDetalle4: "Recomendado para una red de 50 hosts",
    entrada1: "Antena inalámbrica (modelo ac / ax)",
    entrada2: "Botón de reset",
    entrada3: "Botón WLAN / WPS (modelo ac / ax)",
    entrada4: "Indicador LED",
    entrada5: "2 x USB 2.0",
    entrada6: "Puerto WAN 1 x GbE RJ-45",
    entrada7: "Puerto WAN / LAN 1x GbE RJ-45",
    entrada8: "Puerto LAN 5 x GbE RJ-45",
    entrada9: "2 x FXS para VoIP (modelo V)",
    entrada10: "Interruptor de encendido / apagado",
    entrada11: "Entrada de alimentación",
    entrada12: "",
  },
  {
    id: 3,
    categoria:"Routers",
    imagen: "/2962_left_2_H1125.png",
    titulo: "Vigor 2962",
    descripcion1: "2 Ethernet WANs",
    descripcion2: "1 GbE/SFP Combo port",
    descripcion3: "300k NAT Sessions",
    descripcion4: "200 Concurrent VPN",
    descripcion5: "",
    link: "/detalleDeProducto/3",
    subTitulo: "Router confiable para oficinas pequeñas y hogares",
    descripcionLarga:
      "La serie Vigor 2915 es una solución de gestión de red integrada diseñada para pequeñas empresas. La interfaz WAN principal es Gigabit Ethernet y los usuarios pueden agregar una conexión WAN secundaria utilizando el puerto LAN 4, el puerto USB o la interfaz Wi-Fi. La Dual WAN provee balanceo de carga o redundancia de enlaces para garantizar un acceso confiable a Internet. La serie Vigor 2915 también es un servidor VPN robusto para hasta 16 túneles simultáneos. Las funciones de firewall y filtrado de contenido pueden controlar el tráfico de red entrante y saliente, y también ofrece funciones de administración de ancho de banda que optimizan la asignación de ancho de banda y permite el mejor uso del ancho de banda disponible.",
    masInfo: "https://www.draytek.com/products/vigor2915",
    imagen2: "/2915ac_interface.png",
    descripcionDetalle1: "Hasta 2 WAN",
    descripcionDetalle2: "16 VPN",
    descripcionDetalle3: "8 VPN SSL",
    descripcionDetalle4: "30k Sesiones",
    subDescripcionDetalle1: "Balanceo de carga",
    subDescripcionDetalle2: "Rendimiento IPsec de hasta 250 Mbps",
    subDescripcionDetalle3: "Rendimiento de hasta 150 Mbps",
    subDescripcionDetalle4: "Recomendado para una red de 15 hosts",
    entrada1: "Entrada de alimentación",
    entrada2: "Interruptor de encendido / apagado",
    entrada3: "1 x USB 2.0",
    entrada4: "Puerto WAN 1 x GbE RJ-45",
    entrada5: "Puerto LAN 3 x GbE RJ-45",
    entrada6: "Puerto WAN / LAN 1x GbE RJ-45",
    entrada7: "Botón WLAN / WPS (modelo ac)",
    entrada8: "Botón de reset",
    entrada9: "Antena inalámbrica (modelo ac)",
    entrada10: "",
    entrada11: "",
    entrada12: "",
  },
  {
    id: 4,
    categoria:"Routers",
    imagen: "/3910_left_H1125.png",
    titulo: "Vigor3910",
    descripcion1: "6 Gigabit Ethernet WANs",
    descripcion2: "2 10G SFP+ WAN",
    descripcion3: "1000k NAT Sessions",
    descripcion4: "500 Concurrent VPN",
    descripcion5: "",
    link: "/detalleDeProducto/4",
    subTitulo: "Router confiable para oficinas pequeñas y hogares",
    descripcionLarga:
      "La serie Vigor 2915 es una solución de gestión de red integrada diseñada para pequeñas empresas. La interfaz WAN principal es Gigabit Ethernet y los usuarios pueden agregar una conexión WAN secundaria utilizando el puerto LAN 4, el puerto USB o la interfaz Wi-Fi. La Dual WAN provee balanceo de carga o redundancia de enlaces para garantizar un acceso confiable a Internet. La serie Vigor 2915 también es un servidor VPN robusto para hasta 16 túneles simultáneos. Las funciones de firewall y filtrado de contenido pueden controlar el tráfico de red entrante y saliente, y también ofrece funciones de administración de ancho de banda que optimizan la asignación de ancho de banda y permite el mejor uso del ancho de banda disponible.",
    masInfo: "https://www.draytek.com/products/vigor2915",
    imagen2: "/2915ac_interface.png",
    descripcionDetalle1: "Hasta 2 WAN",
    descripcionDetalle2: "16 VPN",
    descripcionDetalle3: "8 VPN SSL",
    descripcionDetalle4: "30k Sesiones",
    subDescripcionDetalle1: "Balanceo de carga",
    subDescripcionDetalle2: "Rendimiento IPsec de hasta 250 Mbps",
    subDescripcionDetalle3: "Rendimiento de hasta 150 Mbps",
    subDescripcionDetalle4: "Recomendado para una red de 15 hosts",
    entrada1: "Entrada de alimentación",
    entrada2: "Interruptor de encendido / apagado",
    entrada3: "1 x USB 2.0",
    entrada4: "Puerto WAN 1 x GbE RJ-45",
    entrada5: "Puerto LAN 3 x GbE RJ-45",
    entrada6: "Puerto WAN / LAN 1x GbE RJ-45",
    entrada7: "Botón WLAN / WPS (modelo ac)",
    entrada8: "Botón de reset",
    entrada9: "Antena inalámbrica (modelo ac)",
    entrada10: "",
    entrada11: "",
    entrada12: "",
  },
];

export const switches = [
  {
    id: 5,
    categoria:"Switches",
    imagen: "/G1080_left_H1125.png",
    titulo: "Vigor Switch G1080",
    descripcion1: "8 GbE ports",
    descripcion2: "Smart Lite",
    descripcion3: "16G Switching Capacity",
    descripcion4: "",
    descripcion5: "",
    link: "/detalleDeProducto/5",
    subTitulo: "Router confiable para oficinas pequeñas y hogares",
    descripcionLarga:
      "La serie Vigor 2915 es una solución de gestión de red integrada diseñada para pequeñas empresas. La interfaz WAN principal es Gigabit Ethernet y los usuarios pueden agregar una conexión WAN secundaria utilizando el puerto LAN 4, el puerto USB o la interfaz Wi-Fi. La Dual WAN provee balanceo de carga o redundancia de enlaces para garantizar un acceso confiable a Internet. La serie Vigor 2915 también es un servidor VPN robusto para hasta 16 túneles simultáneos. Las funciones de firewall y filtrado de contenido pueden controlar el tráfico de red entrante y saliente, y también ofrece funciones de administración de ancho de banda que optimizan la asignación de ancho de banda y permite el mejor uso del ancho de banda disponible.",
    masInfo: "https://www.draytek.com/products/vigor2915",
    imagen2: "/2915ac_interface.png",
    descripcionDetalle1: "Hasta 2 WAN",
    descripcionDetalle2: "16 VPN",
    descripcionDetalle3: "8 VPN SSL",
    descripcionDetalle4: "30k Sesiones",
    subDescripcionDetalle1: "Balanceo de carga",
    subDescripcionDetalle2: "Rendimiento IPsec de hasta 250 Mbps",
    subDescripcionDetalle3: "Rendimiento de hasta 150 Mbps",
    subDescripcionDetalle4: "Recomendado para una red de 15 hosts",
    entrada1: "Entrada de alimentación",
    entrada2: "Interruptor de encendido / apagado",
    entrada3: "1 x USB 2.0",
    entrada4: "Puerto WAN 1 x GbE RJ-45",
    entrada5: "Puerto LAN 3 x GbE RJ-45",
    entrada6: "Puerto WAN / LAN 1x GbE RJ-45",
    entrada7: "Botón WLAN / WPS (modelo ac)",
    entrada8: "Botón de reset",
    entrada9: "Antena inalámbrica (modelo ac)",
    entrada10: "",
    entrada11: "",
    entrada12: "",
  },
  {
    id: 6,
    categoria:"Switches",
    imagen: "/G1282_left_H1125.png",
    titulo: "Vigor Switch G1282",
    descripcion1: "24 GbE ports",
    descripcion2: "4 GbE/SFP Combo ports",
    descripcion3: "Web Smart",
    descripcion4: "56G Switching Capacity",
    descripcion5: "1U Rackmount",
    link: "/detalleDeProducto/6",
    subTitulo: "Router confiable para oficinas pequeñas y hogares",
    descripcionLarga:
      "La serie Vigor 2915 es una solución de gestión de red integrada diseñada para pequeñas empresas. La interfaz WAN principal es Gigabit Ethernet y los usuarios pueden agregar una conexión WAN secundaria utilizando el puerto LAN 4, el puerto USB o la interfaz Wi-Fi. La Dual WAN provee balanceo de carga o redundancia de enlaces para garantizar un acceso confiable a Internet. La serie Vigor 2915 también es un servidor VPN robusto para hasta 16 túneles simultáneos. Las funciones de firewall y filtrado de contenido pueden controlar el tráfico de red entrante y saliente, y también ofrece funciones de administración de ancho de banda que optimizan la asignación de ancho de banda y permite el mejor uso del ancho de banda disponible.",
    masInfo: "https://www.draytek.com/products/vigor2915",
    imagen2: "/2915ac_interface.png",
    descripcionDetalle1: "Hasta 2 WAN",
    descripcionDetalle2: "16 VPN",
    descripcionDetalle3: "8 VPN SSL",
    descripcionDetalle4: "30k Sesiones",
    subDescripcionDetalle1: "Balanceo de carga",
    subDescripcionDetalle2: "Rendimiento IPsec de hasta 250 Mbps",
    subDescripcionDetalle3: "Rendimiento de hasta 150 Mbps",
    subDescripcionDetalle4: "Recomendado para una red de 15 hosts",
    entrada1: "Entrada de alimentación",
    entrada2: "Interruptor de encendido / apagado",
    entrada3: "1 x USB 2.0",
    entrada4: "Puerto WAN 1 x GbE RJ-45",
    entrada5: "Puerto LAN 3 x GbE RJ-45",
    entrada6: "Puerto WAN / LAN 1x GbE RJ-45",
    entrada7: "Botón WLAN / WPS (modelo ac)",
    entrada8: "Botón de reset",
    entrada9: "Antena inalámbrica (modelo ac)",
    entrada10: "",
    entrada11: "",
    entrada12: "",
  },
  {
    id: 7,
    categoria:"Switches",
    imagen: "/G2280x_left_H1125.png",
    titulo: "Vigor Switch G2280x",
    descripcion1: "24 GbE ports",
    descripcion2: "4 10G fiber SFP+",
    descripcion3: "L2+ Managed",
    descripcion4: "128G Switching Capacity",
    descripcion5: "1U Rackmount",
    link: "/detalleDeProducto/7",
    subTitulo: "Router confiable para oficinas pequeñas y hogares",
    descripcionLarga:
      "La serie Vigor 2915 es una solución de gestión de red integrada diseñada para pequeñas empresas. La interfaz WAN principal es Gigabit Ethernet y los usuarios pueden agregar una conexión WAN secundaria utilizando el puerto LAN 4, el puerto USB o la interfaz Wi-Fi. La Dual WAN provee balanceo de carga o redundancia de enlaces para garantizar un acceso confiable a Internet. La serie Vigor 2915 también es un servidor VPN robusto para hasta 16 túneles simultáneos. Las funciones de firewall y filtrado de contenido pueden controlar el tráfico de red entrante y saliente, y también ofrece funciones de administración de ancho de banda que optimizan la asignación de ancho de banda y permite el mejor uso del ancho de banda disponible.",
    masInfo: "https://www.draytek.com/products/vigor2915",
    imagen2: "/2915ac_interface.png",
    descripcionDetalle1: "Hasta 2 WAN",
    descripcionDetalle2: "16 VPN",
    descripcionDetalle3: "8 VPN SSL",
    descripcionDetalle4: "30k Sesiones",
    subDescripcionDetalle1: "Balanceo de carga",
    subDescripcionDetalle2: "Rendimiento IPsec de hasta 250 Mbps",
    subDescripcionDetalle3: "Rendimiento de hasta 150 Mbps",
    subDescripcionDetalle4: "Recomendado para una red de 15 hosts",
    entrada1: "Entrada de alimentación",
    entrada2: "Interruptor de encendido / apagado",
    entrada3: "1 x USB 2.0",
    entrada4: "Puerto WAN 1 x GbE RJ-45",
    entrada5: "Puerto LAN 3 x GbE RJ-45",
    entrada6: "Puerto WAN / LAN 1x GbE RJ-45",
    entrada7: "Botón WLAN / WPS (modelo ac)",
    entrada8: "Botón de reset",
    entrada9: "Antena inalámbrica (modelo ac)",
    entrada10: "",
    entrada11: "",
    entrada12: "",
  },
  {
    id: 8,
    categoria:"Switches",
    imagen: "/G2540x_left_H1125.png",
    titulo: "Vigor Switch G2540xs",
    descripcion1: "48 GbE ports",
    descripcion2: "6 10G fiber SFP+",
    descripcion3: "L2+ Managed",
    descripcion4: "216G Switching Capacity",
    descripcion5: "1U Rackmount",
    link: "/detalleDeProducto/8",
    subTitulo: "Router confiable para oficinas pequeñas y hogares",
    descripcionLarga:
      "La serie Vigor 2915 es una solución de gestión de red integrada diseñada para pequeñas empresas. La interfaz WAN principal es Gigabit Ethernet y los usuarios pueden agregar una conexión WAN secundaria utilizando el puerto LAN 4, el puerto USB o la interfaz Wi-Fi. La Dual WAN provee balanceo de carga o redundancia de enlaces para garantizar un acceso confiable a Internet. La serie Vigor 2915 también es un servidor VPN robusto para hasta 16 túneles simultáneos. Las funciones de firewall y filtrado de contenido pueden controlar el tráfico de red entrante y saliente, y también ofrece funciones de administración de ancho de banda que optimizan la asignación de ancho de banda y permite el mejor uso del ancho de banda disponible.",
    masInfo: "https://www.draytek.com/products/vigor2915",
    imagen2: "/2915ac_interface.png",
    descripcionDetalle1: "Hasta 2 WAN",
    descripcionDetalle2: "16 VPN",
    descripcionDetalle3: "8 VPN SSL",
    descripcionDetalle4: "30k Sesiones",
    subDescripcionDetalle1: "Balanceo de carga",
    subDescripcionDetalle2: "Rendimiento IPsec de hasta 250 Mbps",
    subDescripcionDetalle3: "Rendimiento de hasta 150 Mbps",
    subDescripcionDetalle4: "Recomendado para una red de 15 hosts",
    entrada1: "Entrada de alimentación",
    entrada2: "Interruptor de encendido / apagado",
    entrada3: "1 x USB 2.0",
    entrada4: "Puerto WAN 1 x GbE RJ-45",
    entrada5: "Puerto LAN 3 x GbE RJ-45",
    entrada6: "Puerto WAN / LAN 1x GbE RJ-45",
    entrada7: "Botón WLAN / WPS (modelo ac)",
    entrada8: "Botón de reset",
    entrada9: "Antena inalámbrica (modelo ac)",
    entrada10: "",
    entrada11: "",
    entrada12: "",
  },
  {
    id: 9,
    categoria:"Switches",
    imagen: "/P2100_left_H1125.png",
    titulo: "Vigor Switch P2100",
    descripcion1: "8 PoE/PoE+ GbE ports",
    descripcion2: "2 SFP ports",
    descripcion3: "20G Switching Capacity",
    descripcion4: "140W PoE Power Budget",
    descripcion5: "1U Rackmount",
    link: "/detalleDeProducto/9",
    subTitulo: "Router confiable para oficinas pequeñas y hogares",
    descripcionLarga:
      "La serie Vigor 2915 es una solución de gestión de red integrada diseñada para pequeñas empresas. La interfaz WAN principal es Gigabit Ethernet y los usuarios pueden agregar una conexión WAN secundaria utilizando el puerto LAN 4, el puerto USB o la interfaz Wi-Fi. La Dual WAN provee balanceo de carga o redundancia de enlaces para garantizar un acceso confiable a Internet. La serie Vigor 2915 también es un servidor VPN robusto para hasta 16 túneles simultáneos. Las funciones de firewall y filtrado de contenido pueden controlar el tráfico de red entrante y saliente, y también ofrece funciones de administración de ancho de banda que optimizan la asignación de ancho de banda y permite el mejor uso del ancho de banda disponible.",
    masInfo: "https://www.draytek.com/products/vigor2915",
    imagen2: "/2915ac_interface.png",
    descripcionDetalle1: "Hasta 2 WAN",
    descripcionDetalle2: "16 VPN",
    descripcionDetalle3: "8 VPN SSL",
    descripcionDetalle4: "30k Sesiones",
    subDescripcionDetalle1: "Balanceo de carga",
    subDescripcionDetalle2: "Rendimiento IPsec de hasta 250 Mbps",
    subDescripcionDetalle3: "Rendimiento de hasta 150 Mbps",
    subDescripcionDetalle4: "Recomendado para una red de 15 hosts",
    entrada1: "Entrada de alimentación",
    entrada2: "Interruptor de encendido / apagado",
    entrada3: "1 x USB 2.0",
    entrada4: "Puerto WAN 1 x GbE RJ-45",
    entrada5: "Puerto LAN 3 x GbE RJ-45",
    entrada6: "Puerto WAN / LAN 1x GbE RJ-45",
    entrada7: "Botón WLAN / WPS (modelo ac)",
    entrada8: "Botón de reset",
    entrada9: "Antena inalámbrica (modelo ac)",
    entrada10: "",
    entrada11: "",
    entrada12: "",
  },
  {
    id: 10,
    categoria:"Switches",
    imagen: "/P1282_left_H1125.png",
    titulo: "VigorSwitch P1282",
    descripcion1: "24 PoE/PoE+ GbE ports",
    descripcion2: "4 GbE/SFP Combo ports",
    descripcion3: "Web Smart",
    descripcion4: "56G Switching Capacity",
    descripcion5: "1U Rackmount",
    link: "/detalleDeProducto/10",
    subTitulo: "Router confiable para oficinas pequeñas y hogares",
    descripcionLarga:
      "La serie Vigor 2915 es una solución de gestión de red integrada diseñada para pequeñas empresas. La interfaz WAN principal es Gigabit Ethernet y los usuarios pueden agregar una conexión WAN secundaria utilizando el puerto LAN 4, el puerto USB o la interfaz Wi-Fi. La Dual WAN provee balanceo de carga o redundancia de enlaces para garantizar un acceso confiable a Internet. La serie Vigor 2915 también es un servidor VPN robusto para hasta 16 túneles simultáneos. Las funciones de firewall y filtrado de contenido pueden controlar el tráfico de red entrante y saliente, y también ofrece funciones de administración de ancho de banda que optimizan la asignación de ancho de banda y permite el mejor uso del ancho de banda disponible.",
    masInfo: "https://www.draytek.com/products/vigor2915",
    imagen2: "/2915ac_interface.png",
    descripcionDetalle1: "Hasta 2 WAN",
    descripcionDetalle2: "16 VPN",
    descripcionDetalle3: "8 VPN SSL",
    descripcionDetalle4: "30k Sesiones",
    subDescripcionDetalle1: "Balanceo de carga",
    subDescripcionDetalle2: "Rendimiento IPsec de hasta 250 Mbps",
    subDescripcionDetalle3: "Rendimiento de hasta 150 Mbps",
    subDescripcionDetalle4: "Recomendado para una red de 15 hosts",
    entrada1: "Entrada de alimentación",
    entrada2: "Interruptor de encendido / apagado",
    entrada3: "1 x USB 2.0",
    entrada4: "Puerto WAN 1 x GbE RJ-45",
    entrada5: "Puerto LAN 3 x GbE RJ-45",
    entrada6: "Puerto WAN / LAN 1x GbE RJ-45",
    entrada7: "Botón WLAN / WPS (modelo ac)",
    entrada8: "Botón de reset",
    entrada9: "Antena inalámbrica (modelo ac)",
    entrada10: "",
    entrada11: "",
    entrada12: "",
  },
];

export const puntosDeAcceso = [
  {
    id: 11,
    categoria:"Puntos de Acceso",
    imagen: "/AP903_left_H1125.png",
    titulo: "Vigor AP 903",
    descripcion1: "11ac Wave 2 Dual Band",
    descripcion2: "Maximum Data Rate: 1.3 Gbps",
    descripcion3: " Wall/Desktop Mount",
    descripcion4: "",
    descripcion5: "",
    link: "/detalleDeProducto/11",
    subTitulo: "Router confiable para oficinas pequeñas y hogares",
    descripcionLarga:
      "La serie Vigor 2915 es una solución de gestión de red integrada diseñada para pequeñas empresas. La interfaz WAN principal es Gigabit Ethernet y los usuarios pueden agregar una conexión WAN secundaria utilizando el puerto LAN 4, el puerto USB o la interfaz Wi-Fi. La Dual WAN provee balanceo de carga o redundancia de enlaces para garantizar un acceso confiable a Internet. La serie Vigor 2915 también es un servidor VPN robusto para hasta 16 túneles simultáneos. Las funciones de firewall y filtrado de contenido pueden controlar el tráfico de red entrante y saliente, y también ofrece funciones de administración de ancho de banda que optimizan la asignación de ancho de banda y permite el mejor uso del ancho de banda disponible.",
    masInfo: "https://www.draytek.com/products/vigor2915",
    imagen2: "/2915ac_interface.png",
    descripcionDetalle1: "Hasta 2 WAN",
    descripcionDetalle2: "16 VPN",
    descripcionDetalle3: "8 VPN SSL",
    descripcionDetalle4: "30k Sesiones",
    subDescripcionDetalle1: "Balanceo de carga",
    subDescripcionDetalle2: "Rendimiento IPsec de hasta 250 Mbps",
    subDescripcionDetalle3: "Rendimiento de hasta 150 Mbps",
    subDescripcionDetalle4: "Recomendado para una red de 15 hosts",
    entrada1: "Entrada de alimentación",
    entrada2: "Interruptor de encendido / apagado",
    entrada3: "1 x USB 2.0",
    entrada4: "Puerto WAN 1 x GbE RJ-45",
    entrada5: "Puerto LAN 3 x GbE RJ-45",
    entrada6: "Puerto WAN / LAN 1x GbE RJ-45",
    entrada7: "Botón WLAN / WPS (modelo ac)",
    entrada8: "Botón de reset",
    entrada9: "Antena inalámbrica (modelo ac)",
    entrada10: "",
    entrada11: "",
    entrada12: "",
  },
  {
    id: 12,
    categoria:"Puntos de Acceso",
    imagen: "/AP906_left_H1125.png",
    titulo: "Vigor AP 906",
    descripcion1: "11ax Dual-Band",
    descripcion2: "Maximum Data Rate: 3 Gbps",
    descripcion3: "Wall/Desktop Mount",
    descripcion4: "",
    descripcion5: "",
    link: "/detalleDeProducto/12",
    subTitulo: "Router confiable para oficinas pequeñas y hogares",
    descripcionLarga:
      "La serie Vigor 2915 es una solución de gestión de red integrada diseñada para pequeñas empresas. La interfaz WAN principal es Gigabit Ethernet y los usuarios pueden agregar una conexión WAN secundaria utilizando el puerto LAN 4, el puerto USB o la interfaz Wi-Fi. La Dual WAN provee balanceo de carga o redundancia de enlaces para garantizar un acceso confiable a Internet. La serie Vigor 2915 también es un servidor VPN robusto para hasta 16 túneles simultáneos. Las funciones de firewall y filtrado de contenido pueden controlar el tráfico de red entrante y saliente, y también ofrece funciones de administración de ancho de banda que optimizan la asignación de ancho de banda y permite el mejor uso del ancho de banda disponible.",
    masInfo: "https://www.draytek.com/products/vigor2915",
    imagen2: "/2915ac_interface.png",
    descripcionDetalle1: "Hasta 2 WAN",
    descripcionDetalle2: "16 VPN",
    descripcionDetalle3: "8 VPN SSL",
    descripcionDetalle4: "30k Sesiones",
    subDescripcionDetalle1: "Balanceo de carga",
    subDescripcionDetalle2: "Rendimiento IPsec de hasta 250 Mbps",
    subDescripcionDetalle3: "Rendimiento de hasta 150 Mbps",
    subDescripcionDetalle4: "Recomendado para una red de 15 hosts",
    entrada1: "Entrada de alimentación",
    entrada2: "Interruptor de encendido / apagado",
    entrada3: "1 x USB 2.0",
    entrada4: "Puerto WAN 1 x GbE RJ-45",
    entrada5: "Puerto LAN 3 x GbE RJ-45",
    entrada6: "Puerto WAN / LAN 1x GbE RJ-45",
    entrada7: "Botón WLAN / WPS (modelo ac)",
    entrada8: "Botón de reset",
    entrada9: "Antena inalámbrica (modelo ac)",
    entrada10: "",
    entrada11: "",
    entrada12: "",
  },
  {
    id: 13,
    categoria:"Puntos de Acceso",
    imagen: "/912C_top_2_H1125.png",
    titulo: "VigorAP 912C",
    descripcion1: "11ac Wave 2 Dual Band",
    descripcion2: "Maximum Data Rate: 1.3 Gbps",
    descripcion3: "Wall/Ceiling Mount",
    descripcion4: "",
    descripcion5: "",
    link: "/detalleDeProducto/13",
    subTitulo: "Router confiable para oficinas pequeñas y hogares",
    descripcionLarga:
      "La serie Vigor 2915 es una solución de gestión de red integrada diseñada para pequeñas empresas. La interfaz WAN principal es Gigabit Ethernet y los usuarios pueden agregar una conexión WAN secundaria utilizando el puerto LAN 4, el puerto USB o la interfaz Wi-Fi. La Dual WAN provee balanceo de carga o redundancia de enlaces para garantizar un acceso confiable a Internet. La serie Vigor 2915 también es un servidor VPN robusto para hasta 16 túneles simultáneos. Las funciones de firewall y filtrado de contenido pueden controlar el tráfico de red entrante y saliente, y también ofrece funciones de administración de ancho de banda que optimizan la asignación de ancho de banda y permite el mejor uso del ancho de banda disponible.",
    masInfo: "https://www.draytek.com/products/vigor2915",
    imagen2: "/2915ac_interface.png",
    descripcionDetalle1: "Hasta 2 WAN",
    descripcionDetalle2: "16 VPN",
    descripcionDetalle3: "8 VPN SSL",
    descripcionDetalle4: "30k Sesiones",
    subDescripcionDetalle1: "Balanceo de carga",
    subDescripcionDetalle2: "Rendimiento IPsec de hasta 250 Mbps",
    subDescripcionDetalle3: "Rendimiento de hasta 150 Mbps",
    subDescripcionDetalle4: "Recomendado para una red de 15 hosts",
    entrada1: "Entrada de alimentación",
    entrada2: "Interruptor de encendido / apagado",
    entrada3: "1 x USB 2.0",
    entrada4: "Puerto WAN 1 x GbE RJ-45",
    entrada5: "Puerto LAN 3 x GbE RJ-45",
    entrada6: "Puerto WAN / LAN 1x GbE RJ-45",
    entrada7: "Botón WLAN / WPS (modelo ac)",
    entrada8: "Botón de reset",
    entrada9: "Antena inalámbrica (modelo ac)",
    entrada10: "",
    entrada11: "",
    entrada12: "",
  },
  {
    id: 14,
    categoria:"Puntos de Acceso",
    imagen: "/918R_left_H1125.png",
    titulo: "Vigor AP 918R Series",
    descripcion1: "11ac Wave 2 Dual Band",
    descripcion2: "Maximum Data Rate: 1.3 Gbps",
    descripcion3: "Wall/Pole Mount",
    descripcion4: "IP67 Rated Waterproof",
    descripcion5: "",
    link: "/detalleDeProducto/14",
    subTitulo: "Router confiable para oficinas pequeñas y hogares",
    descripcionLarga:
      "La serie Vigor 2915 es una solución de gestión de red integrada diseñada para pequeñas empresas. La interfaz WAN principal es Gigabit Ethernet y los usuarios pueden agregar una conexión WAN secundaria utilizando el puerto LAN 4, el puerto USB o la interfaz Wi-Fi. La Dual WAN provee balanceo de carga o redundancia de enlaces para garantizar un acceso confiable a Internet. La serie Vigor 2915 también es un servidor VPN robusto para hasta 16 túneles simultáneos. Las funciones de firewall y filtrado de contenido pueden controlar el tráfico de red entrante y saliente, y también ofrece funciones de administración de ancho de banda que optimizan la asignación de ancho de banda y permite el mejor uso del ancho de banda disponible.",
    masInfo: "https://www.draytek.com/products/vigor2915",
    imagen2: "/2915ac_interface.png",
    descripcionDetalle1: "Hasta 2 WAN",
    descripcionDetalle2: "16 VPN",
    descripcionDetalle3: "8 VPN SSL",
    descripcionDetalle4: "30k Sesiones",
    subDescripcionDetalle1: "Balanceo de carga",
    subDescripcionDetalle2: "Rendimiento IPsec de hasta 250 Mbps",
    subDescripcionDetalle3: "Rendimiento de hasta 150 Mbps",
    subDescripcionDetalle4: "Recomendado para una red de 15 hosts",
    entrada1: "Entrada de alimentación",
    entrada2: "Interruptor de encendido / apagado",
    entrada3: "1 x USB 2.0",
    entrada4: "Puerto WAN 1 x GbE RJ-45",
    entrada5: "Puerto LAN 3 x GbE RJ-45",
    entrada6: "Puerto WAN / LAN 1x GbE RJ-45",
    entrada7: "Botón WLAN / WPS (modelo ac)",
    entrada8: "Botón de reset",
    entrada9: "Antena inalámbrica (modelo ac)",
    entrada10: "",
    entrada11: "",
    entrada12: "",
  },
];

export const accesorios = [
  {
    id: 15,
    categoria:"Accesorios",
    imagen: "/rack_mount_bracket.png",
    titulo: "Rack Mount Bracket",
    descripcion1: "Make the router mountable for a standard 19 inch rack",
    descripcion2: "",
    descripcion3: "",
    descripcion4: "",
    descripcion5: "",
    link: "/detalleDeProducto/15",
    subTitulo: "Router confiable para oficinas pequeñas y hogares",
    descripcionLarga:
      "La serie Vigor 2915 es una solución de gestión de red integrada diseñada para pequeñas empresas. La interfaz WAN principal es Gigabit Ethernet y los usuarios pueden agregar una conexión WAN secundaria utilizando el puerto LAN 4, el puerto USB o la interfaz Wi-Fi. La Dual WAN provee balanceo de carga o redundancia de enlaces para garantizar un acceso confiable a Internet. La serie Vigor 2915 también es un servidor VPN robusto para hasta 16 túneles simultáneos. Las funciones de firewall y filtrado de contenido pueden controlar el tráfico de red entrante y saliente, y también ofrece funciones de administración de ancho de banda que optimizan la asignación de ancho de banda y permite el mejor uso del ancho de banda disponible.",
    masInfo: "https://www.draytek.com/products/vigor2915",
    imagen2: "/2915ac_interface.png",
    descripcionDetalle1: "Hasta 2 WAN",
    descripcionDetalle2: "16 VPN",
    descripcionDetalle3: "8 VPN SSL",
    descripcionDetalle4: "30k Sesiones",
    subDescripcionDetalle1: "Balanceo de carga",
    subDescripcionDetalle2: "Rendimiento IPsec de hasta 250 Mbps",
    subDescripcionDetalle3: "Rendimiento de hasta 150 Mbps",
    subDescripcionDetalle4: "Recomendado para una red de 15 hosts",
    entrada1: "Entrada de alimentación",
    entrada2: "Interruptor de encendido / apagado",
    entrada3: "1 x USB 2.0",
    entrada4: "Puerto WAN 1 x GbE RJ-45",
    entrada5: "Puerto LAN 3 x GbE RJ-45",
    entrada6: "Puerto WAN / LAN 1x GbE RJ-45",
    entrada7: "Botón WLAN / WPS (modelo ac)",
    entrada8: "Botón de reset",
    entrada9: "Antena inalámbrica (modelo ac)",
    entrada10: "",
    entrada11: "",
    entrada12: "",
  },
  {
    id: 16,
    categoria:"Accesorios",
    imagen: "/dac-cx10.png",
    titulo: "DAC-CX10",
    descripcion1: "1m/3m 10G SFP+ direct attach passive copper cable",
    descripcion2: "",
    descripcion3: "",
    descripcion4: "",
    descripcion5: "",
    link: "/detalleDeProducto/16",
    subTitulo: "Router confiable para oficinas pequeñas y hogares",
    descripcionLarga:
      "La serie Vigor 2915 es una solución de gestión de red integrada diseñada para pequeñas empresas. La interfaz WAN principal es Gigabit Ethernet y los usuarios pueden agregar una conexión WAN secundaria utilizando el puerto LAN 4, el puerto USB o la interfaz Wi-Fi. La Dual WAN provee balanceo de carga o redundancia de enlaces para garantizar un acceso confiable a Internet. La serie Vigor 2915 también es un servidor VPN robusto para hasta 16 túneles simultáneos. Las funciones de firewall y filtrado de contenido pueden controlar el tráfico de red entrante y saliente, y también ofrece funciones de administración de ancho de banda que optimizan la asignación de ancho de banda y permite el mejor uso del ancho de banda disponible.",
    masInfo: "https://www.draytek.com/products/vigor2915",
    imagen2: "/2915ac_interface.png",
    descripcionDetalle1: "Hasta 2 WAN",
    descripcionDetalle2: "16 VPN",
    descripcionDetalle3: "8 VPN SSL",
    descripcionDetalle4: "30k Sesiones",
    subDescripcionDetalle1: "Balanceo de carga",
    subDescripcionDetalle2: "Rendimiento IPsec de hasta 250 Mbps",
    subDescripcionDetalle3: "Rendimiento de hasta 150 Mbps",
    subDescripcionDetalle4: "Recomendado para una red de 15 hosts",
    entrada1: "Entrada de alimentación",
    entrada2: "Interruptor de encendido / apagado",
    entrada3: "1 x USB 2.0",
    entrada4: "Puerto WAN 1 x GbE RJ-45",
    entrada5: "Puerto LAN 3 x GbE RJ-45",
    entrada6: "Puerto WAN / LAN 1x GbE RJ-45",
    entrada7: "Botón WLAN / WPS (modelo ac)",
    entrada8: "Botón de reset",
    entrada9: "Antena inalámbrica (modelo ac)",
    entrada10: "",
    entrada11: "",
    entrada12: "",
  },
  {
    id: 17,
    categoria:"Accesorios",
    imagen: "/URL_Reputation.webp",
    titulo: "URL Reputation",
    descripcion1: "Threat Intelligence Service",
    descripcion2: "",
    descripcion3: "",
    descripcion4: "",
    descripcion5: "",
    link: "/detalleDeProducto/17",
    subTitulo: "Router confiable para oficinas pequeñas y hogares",
    descripcionLarga:
      "La serie Vigor 2915 es una solución de gestión de red integrada diseñada para pequeñas empresas. La interfaz WAN principal es Gigabit Ethernet y los usuarios pueden agregar una conexión WAN secundaria utilizando el puerto LAN 4, el puerto USB o la interfaz Wi-Fi. La Dual WAN provee balanceo de carga o redundancia de enlaces para garantizar un acceso confiable a Internet. La serie Vigor 2915 también es un servidor VPN robusto para hasta 16 túneles simultáneos. Las funciones de firewall y filtrado de contenido pueden controlar el tráfico de red entrante y saliente, y también ofrece funciones de administración de ancho de banda que optimizan la asignación de ancho de banda y permite el mejor uso del ancho de banda disponible.",
    masInfo: "https://www.draytek.com/products/vigor2915",
    imagen2: "/2915ac_interface.png",
    descripcionDetalle1: "Hasta 2 WAN",
    descripcionDetalle2: "16 VPN",
    descripcionDetalle3: "8 VPN SSL",
    descripcionDetalle4: "30k Sesiones",
    subDescripcionDetalle1: "Balanceo de carga",
    subDescripcionDetalle2: "Rendimiento IPsec de hasta 250 Mbps",
    subDescripcionDetalle3: "Rendimiento de hasta 150 Mbps",
    subDescripcionDetalle4: "Recomendado para una red de 15 hosts",
    entrada1: "Entrada de alimentación",
    entrada2: "Interruptor de encendido / apagado",
    entrada3: "1 x USB 2.0",
    entrada4: "Puerto WAN 1 x GbE RJ-45",
    entrada5: "Puerto LAN 3 x GbE RJ-45",
    entrada6: "Puerto WAN / LAN 1x GbE RJ-45",
    entrada7: "Botón WLAN / WPS (modelo ac)",
    entrada8: "Botón de reset",
    entrada9: "Antena inalámbrica (modelo ac)",
    entrada10: "",
    entrada11: "",
    entrada12: "",
  },
];
