export const categorias = [
  {
    id: 1,
    titulo: "Routers",
    imagen: "/Routers.png",
    link: "/Routers",
  },
  {
    id: 2,
    titulo: "Swithes",
    imagen: "/Swithes.png",
    link: "/Switches",
  },
  {
    id: 3,
    titulo: "Puntos de Acceso",
    imagen: "/PuntosAcceso.png",
    link: "/PuntosDeAcceso",
  },
  {
    id: 4,
    titulo: "Accesorios",
    imagen: "/Accesorios.png",
    link: "/Accesorios",
  },
];

export const routers = [
  {
    id: 1,
    imagen: "/2915ac_left_H1125.png",
    titulo: "Vigor 2915 Series",
    descripcion1: "Dual Gigabit Ethernet WANs",
    descripcion2: "30k NAT Sessions",
    descripcion3: "16 Concurrent VPN",
    descripcion4: "Built-in 11ac Wave 2 WLAN (optional)",
    descripcion5: "",
    link: "/Routers/:id",
  },
  {
    id: 2,
    imagen: "/2927ac_left_new_H1125.png",
    titulo: "Vigor 2927 Series",
    descripcion1: "Dual Gigabit Ethernet WANs",
    descripcion2: "60k NAT Sessions",
    descripcion3: "50 Concurrent VPN",
    descripcion4: "Built-in 11ac Wave 2 WLAN (optional)",
    descripcion5: "Built-in 11ax WLAN (optional)",
    link: "/Routers/:id",
  },
  {
    id: 3,
    imagen: "/2962_left_2_H1125.png",
    titulo: "Vigor 2962",
    descripcion1: "2 Ethernet WANs",
    descripcion2: "1 GbE/SFP Combo port",
    descripcion3: "300k NAT Sessions",
    descripcion4: "200 Concurrent VPN",
    descripcion5: "",
    link: "/Routers/:id",
  },
  {
    id: 4,
    imagen: "/3910_left_H1125.png",
    titulo: "Vigor3910",
    descripcion1: "6 Gigabit Ethernet WANs",
    descripcion2: "2 10G SFP+ WAN",
    descripcion3: "1000k NAT Sessions",
    descripcion4: "500 Concurrent VPN",
    descripcion5: "",
    link: "/Routers/:id",
  },
];

export const switches = [
  {
    id: 1,
    imagen: "/G1080_left_H1125.png",
    titulo: "Vigor Switch G1080",
    descripcion1: "8 GbE ports",
    descripcion2: "Smart Lite",
    descripcion3: "16G Switching Capacity",
    descripcion4: "",
    descripcion5: "",
    link: "/Switches/:id",
  },
  {
    id: 2,
    imagen: "/G1282_left_H1125.png",
    titulo: "Vigor Switch G1282",
    descripcion1: "24 GbE ports",
    descripcion2: "4 GbE/SFP Combo ports",
    descripcion3: "Web Smart",
    descripcion4: "56G Switching Capacity",
    descripcion5: "1U Rackmount",
    link: "/Switches/:id",
  },
  {
    id: 3,
    imagen: "/G2280x_left_H1125.png",
    titulo: "Vigor Switch G2280x",
    descripcion1: "24 GbE ports",
    descripcion2: "4 10G fiber SFP+",
    descripcion3: "L2+ Managed",
    descripcion4: "128G Switching Capacity",
    descripcion5: "1U Rackmount",
    link: "/Switches/:id",
  },
  {
    id: 4,
    imagen: "/G2540x_left_H1125.png",
    titulo: "Vigor Switch G2540xs",
    descripcion1: "48 GbE ports",
    descripcion2: "6 10G fiber SFP+",
    descripcion3: "L2+ Managed",
    descripcion4: "216G Switching Capacity",
    descripcion5: "1U Rackmount",
    link: "/Switches/:id",
  },
  {
    id: 5,
    imagen: "/P2100_left_H1125.png",
    titulo: "Vigor Switch P2100",
    descripcion1: "8 PoE/PoE+ GbE ports",
    descripcion2: "2 SFP ports",
    descripcion3: "20G Switching Capacity",
    descripcion4: "140W PoE Power Budget",
    descripcion5: "1U Rackmount",
    link: "/Switches/:id",
  },
  {
    id: 6,
    imagen: "/P1282_left_H1125.png",
    titulo: "VigorSwitch P1282",
    descripcion1: "24 PoE/PoE+ GbE ports",
    descripcion2: "4 GbE/SFP Combo ports",
    descripcion3: "Web Smart",
    descripcion4: "56G Switching Capacity",
    descripcion5: "1U Rackmount",
    link: "/Switches/:id",
  },
];

export const puntosDeAcceso = [
    {
        id: 1,
        imagen: "/AP903_left_H1125.png",
        titulo: "Vigor AP 903",
        descripcion1: "11ac Wave 2 Dual Band",
        descripcion2: "Maximum Data Rate: 1.3 Gbps",
        descripcion3: " Wall/Desktop Mount",
        descripcion4: "",
        descripcion5: "",
        link: "/PuntosDeAcceso/:id",
      },
      {
        id: 2,
        imagen: "/AP906_left_H1125.png",
        titulo: "Vigor AP 906",
        descripcion1: "11ax Dual-Band",
        descripcion2: "Maximum Data Rate: 3 Gbps",
        descripcion3: "Wall/Desktop Mount",
        descripcion4: "",
        descripcion5: "",
        link: "/PuntosDeAcceso/:id",
      },
      {
        id: 3,
        imagen: "/912C_top_2_H1125.png",
        titulo: "VigorAP 912C",
        descripcion1: "11ac Wave 2 Dual Band",
        descripcion2: "Maximum Data Rate: 1.3 Gbps",
        descripcion3: "Wall/Ceiling Mount",
        descripcion4: "",
        descripcion5: "",
        link: "/PuntosDeAcceso/:id",
      },
      {
        id: 4,
        imagen: "/918R_left_H1125.png",
        titulo: "Vigor AP 918R Series",
        descripcion1: "11ac Wave 2 Dual Band",
        descripcion2: "Maximum Data Rate: 1.3 Gbps",
        descripcion3: "Wall/Pole Mount",
        descripcion4: "IP67 Rated Waterproof",
        descripcion5: "",
        link: "/PuntosDeAcceso/:id",
      },
];

export const accesorios = [
    {
        id: 1,
        imagen: "/rack_mount_bracket.png",
        titulo: "Rack Mount Bracket",
        descripcion1: "Make the router mountable for a standard 19 inch rack",
        descripcion2: "",
        descripcion3: "",
        descripcion4: "",
        descripcion5: "",
        link: "/accesorios/:id",
      },
      {
        id: 2,
        imagen: "/dac-cx10.png",
        titulo: "DAC-CX10",
        descripcion1: "1m/3m 10G SFP+ direct attach passive copper cable",
        descripcion2: "",
        descripcion3: "",
        descripcion4: "",
        descripcion5: "",
        link: "/accesorios/:id",
      },
      {
        id: 3,
        imagen: "/URL_Reputation.webp",
        titulo: "URL Reputation",
        descripcion1: "Threat Intelligence Service",
        descripcion2: "",
        descripcion3: "",
        descripcion4: "",
        descripcion5: "",
        link: "/accesorios/:id",
      },
];
